apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-container
        image: REPLACE_ME
        ports:
        - containerPort: 3000

        # ✅ Montamos los archivos desde Key Vault
        volumeMounts:
        - name: secrets-store-volume
          mountPath: "/mnt/secrets-store"
          readOnly: true

        # ✅ Inyectamos variables de entorno desde los archivos secretos
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: DB-USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: DB-PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: DB-HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: kv-secrets
              key: DB-NAME

      volumes:
      - name: secrets-store-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kv-secrets"

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
