apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: kv-secrets
      type: Opaque
      data:
        - key: DB-USER
          objectName: DB-USER
        - key: DB-PASSWORD
          objectName: DB-PASSWORD
        - key: DB-HOST
          objectName: DB-HOST
        - key: DB-NAME
          objectName: DB-NAME
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "b2c07e93-89f1-479a-8516-1826335a1954"
    keyvaultName: kv-terra-demo
    tenantId: fb43d70d-43c8-44cc-a870-6592e9748e0b
    objects: |
      array:
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret