name: CI/CD Node App to AKS

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RG }}
        cluster-name: ${{ secrets.AKS_NAME }}

    - name: Deploy to AKS
      run: |
        sed "s|REPLACE_ME|${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" app.yaml > app.generated.yaml
        kubectl apply -f app.generated.yaml

    - name: Provide Permission to AKS to pull from ACR
      run: |
        az aks update --name aks-demo-cluster --resource-group RG-Terraform-Demo --attach-acr myacrterraformdemo

    - name: Uninstall old provider (optional)
      run: |
        set +e  # desactiva la detención automática por errores

        # Verifica si el release existe y está en estado válido
        helm status csi-secrets-store-provider-azure -n kube-system > /dev/null 2>&1
        STATUS_RESULT=$?

        if [ $STATUS_RESULT -eq 0 ]; then
          echo "Previous release found. Uninstalling..."
          helm uninstall csi-secrets-store-provider-azure -n kube-system
          UNINSTALL_RESULT=$?
          if [ $UNINSTALL_RESULT -ne 0 ]; then
            echo "⚠️ Warning: Uninstall command failed, but continuing anyway..."
          fi
        else
          echo "No previous release found or already deleted."
        fi

        set -e  # reactiva el fallo automático



    - name: Install or upgrade CSI driver + Azure Key Vault Provider
      run: |
        helm repo add csi-azure https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
        helm repo update
        helm upgrade --install csi-secrets-store csi-azure/csi-secrets-store-provider-azure --namespace kube-system

    - name: Apply SecretProviderClass
      run: kubectl apply -f secret-provider.yaml
