name: CI/CD Node App to AKS

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RG }}
        cluster-name: ${{ secrets.AKS_NAME }}

    - name: Deploy to AKS
      run: |
        sed "s|REPLACE_ME|${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" app.yaml > app.generated.yaml
        kubectl apply -f app.generated.yaml

    - name: Provide Permission to AKS to pull from ACR
      run: |
        az aks update --name aks-demo-cluster --resource-group RG-Terraform-Demo --attach-acr myacrterraformdemo

    - name: Install CSI secrets-store-csi-driver
      run: |
        helm uninstall csi-secrets-store-provider-azure -n kube-system
        helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
        helm repo update
        helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system

- name: Install Azure Key Vault Provider
  run: |
    kubectl apply -f https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/main/deployment/azureprovider.yaml

    - name: Apply SecretProviderClass
      run: kubectl apply -f secret-provider.yaml
