name: CI/CD Node App to AKS

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RG }}
        cluster-name: ${{ secrets.AKS_NAME }}

    - name: Deploy to AKS
      run: |
        sed "s|REPLACE_ME|${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" app.yaml > app.generated.yaml
        kubectl apply -f app.generated.yaml

    - name: Provide Permission to AKS to pull from ACR
      run: |
        az aks update --name aks-demo-cluster --resource-group RG-Terraform-Demo --attach-acr myacrterraformdemo

    - name: Uninstall old provider (optional)
      run: |
        set +e  # desactiva la detención automática por errores

        # Verifica si el release existe y está en estado válido
        helm status csi-secrets-store-provider-azure -n kube-system > /dev/null 2>&1
        STATUS_RESULT=$?

        if [ $STATUS_RESULT -eq 0 ]; then
          echo "Previous release found. Uninstalling..."
          helm uninstall csi-secrets-store-provider-azure -n kube-system
          UNINSTALL_RESULT=$?
          if [ $UNINSTALL_RESULT -ne 0 ]; then
            echo "⚠️ Warning: Uninstall command failed, but continuing anyway..."
          fi
        else
          echo "No previous release found or already deleted."
        fi

        set -e  # reactiva el fallo automático

    - name: Add CSI driver Helm repo
      run: |
        helm repo add csi-azure https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
        helm repo update

    - name: Install/Upgrade CSI Secrets Store Driver (Kubernetes CSI layer)
      run: |
        helm upgrade --install csi-secrets-store csi-azure/csi-secrets-store-provider-azure \
          --namespace kube-system

    - name: Ensure CSI Key Vault Secrets Provider addon is enabled
      run: |
        if ! az aks show \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_NAME }} \
            --query "addonProfiles.azureKeyvaultSecretsProvider.enabled" \
            --output tsv | grep -q true; then

          echo "🔧 Enabling azure-keyvault-secrets-provider addon..."
          az aks enable-addons \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_NAME }} \
            --addons azure-keyvault-secrets-provider \
            --enable-secret-rotation
        else
          echo "✅ Addon already enabled. Skipping..."
        fi

    - name: Apply SecretProviderClass inline (string-safe)
      run: |
        kubectl delete secretproviderclass azure-kv-secrets --ignore-not-found

        echo '
        apiVersion: secrets-store.csi.x-k8s.io/v1
        kind: SecretProviderClass
        metadata:
          name: azure-kv-secrets
          namespace: default
        spec:
          provider: azure
          secretObjects:
            - secretName: kv-secrets
              type: Opaque
              data:
                - objectName: DB-USER
                  key: DB-USER
                - objectName: DB-PASSWORD
                  key: DB-PASSWORD
                - objectName: DB-HOST
                  key: DB-HOST
                - objectName: DB-NAME
                  key: DB-NAME
          parameters:
            usePodIdentity: "false"
            useVMManagedIdentity: "true"
            userAssignedIdentityID: ""
            keyvaultName: kv-terra-demo
            tenantId: fb43d70d-43c8-44cc-a870-6592e9748e0b
            objects: |
              - objectName: DB-USER
                objectType: secret
              - objectName: DB-PASSWORD
                objectType: secret
              - objectName: DB-HOST
                objectType: secret
              - objectName: DB-NAME
                objectType: secret
        ' | kubectl apply -f -

    - name: Restart deployment to re-trigger secret mount
      run: |
        kubectl rollout restart deployment node-app
